### ISSUE TITLE
pip安装的直接Example的代码跑不起来

### ISSUE THREAD

**Issue by maokecheng** [synodriver/pytea#2]
tea = pytea.TEA(secret_key=bytes(16), encrypt_times=16)   
TypeError: __init__() got an unexpected keyword argument 'secret_key'

any idea?

**Comment by synodriver** [comment]
版本有吗？是rc版本？

**Comment by synodriver** [comment]
别用kw参数呢？

**Comment by synodriver** [comment]
是Cython编译优化问题。Cython为了优化，默认不允许kw参数，参见[这个问题](https://github.com/cython/cython/issues/2881)
所以，改成
```
tea = pytea.TEA(bytes(16))
```

**Comment by synodriver** [comment]
另外可以试试action的cdivision分支的最新版，根据[cython的说法](https://github.com/cython/cython/wiki/enhancements-division)，这样要快一些，但是在benchmark中并没有发现有显著的提升，因此，0.2.0rc1主要是修复了全局key的历史遗留问题，同时让速度有了更大的提升：达到了py版本的370倍速度

**Comment by synodriver** [comment]
我懂了，安装指令是```pip install pytea2```，因为我名字被抢了（

**Comment by synodriver** [comment]
Consider resolved, close.
